layout_spectrum: 0.9157706
color:
  saturation: 0.8799283
  brandStrength: 0.3870968
  lightness: 0.0358423
  brandColors:
    - '#1E0E06'
    - '#F3FFFF'
    - '#912805'
    - '#5C655C'
    - '#F2FF04'
  rhythmicContrast: 0.7240143
typography_spectrum: 0.3082437
name: The Hedonist
